### ISSUE TITLE
Does not work for the GoLand IDE

### ISSUE THREAD

**Issue by bk800** [syuchan1005/RevealInProjectView#1]
I tried this with GoLand (An IDE by JetBrains for editing Go files), and it did not work.

What I Did:
1) Open a file in my project.  
2) R-Click some where on the file.  
3) Did not see an option for "Reveal in Project View".

**Comment by syuchan1005** [comment]
@bk800
Thanks issue.

I release version 1.0.1 today. However, an intellij team review may require more than two days.
Please wait.

**Comment by bk800** [comment]
@syuchan1005 
Thanks for the quick update!

With 1.0.1, I see the menu option, but it does not seem to be clickable:

![image](https://user-images.githubusercontent.com/21371147/67326779-d88a6e00-f4cb-11e9-83b8-bfa9407fe796.png)

**Comment by bk800** [comment]
Hi, Actually, it does work in most cases.  In my project window, I had selected "Project" in the drop-down list, and saw the above problem.  However, if I select "Project Files", the plugin works great.  Thank you for creating it.

![image](https://user-images.githubusercontent.com/21371147/67420412-6c6b4100-f583-11e9-8422-33b62b4ab99b.png)
